=== houda09122002/houda09122002.github.io/data/video.dtd
<!ELEMENT videoPage (header, video, footer)>
<!ELEMENT header (title, description)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT video (url, embedUrl)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT embedUrl (#PCDATA)>
<!ELEMENT footer (author, date)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== houda09122002/houda09122002.github.io/data/video.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoPage SYSTEM "video.dtd">
<videoPage>
  <header>
    <title>Vidéo de présentation</title>
    <description>Présentation multilingue de Houda Khiati</description>
  </header>
  <video>
    <url>https://www.youtube.com/watch?v=yYJ0z5aeprU</url>
    <embedUrl>https://www.youtube.com/embed/yYJ0z5aeprU</embedUrl>
  </video>
  <footer>
    <author>Houda Khiati</author>
    <date>2025-06-21</date>
  </footer>
</videoPage>
